<div id="extensions">
    <fieldset class="lft">
        <legend>Components</legend>
        <table>
            <tr>
                <th>Component</th>
                <th>Show in menu</th>
            <tr>
                <td></td>
                <td></td>
            </tr>
            </tr>
        </table>
    </fieldset>
    <fieldset class="lft">
        <legend>Sections</legend>
        <table>
            <tr>
                <th>Section</th>
                <th>Position</th>
            <tr>
                <td></td>
                <td></td>
            </tr>
            </tr>
        </table>
    </fieldset>
</div>