<?php
$attributes = array('class' => 'gf', 'id' => 'reset_password_form');
echo form_open('/cc/user/reset_password', $attributes);
?>
<label><span><?php echo lang('email') ?></span><input type="email" name="email" id="email" maxlength="254" required="" /></label>
<label><span><?php echo lang('password') ?></span><input type="password" name="password" maxlength="75" required="" /></label>
<label><button type="submit" name="submit" value="register"><?php echo lang('reset_password') ?></button></label>
</form>