<?php
$add_context = site_url('/cc/context/create_form/' . $context);
$add_topic = site_url('/cc/topic/add_form/' . $context);
$add_lng = lang('add');

$ld = <<<PQR
<a href="#" id="add">+</a>
<ul id="add_opt">
    <li><a href="{$add_context}">{$add_lng} {$context_label}</a></li>
    <li><a href="{$add_topic}">{$add_lng} {$topic_label}</a></li>
</ul>
PQR;
echo logged_data($participants, $ld);
?>

<h3><?php echo lang('details'); ?></h3>
<ul id="details">
    <?php
    echo <<<PQR
    <li><b>Resp.: </b> {$info['info']['responsible']}</li>
PQR;
    ?>
</ul>
<div id="contexts">
    <h3><?php echo $context_label ?></h3>
    <ul>
        <?php
        foreach ($info['contexts'] as $context_slug => $context_info) {
            if (!belongs_to('context', $context_slug, connected_user())) {
                continue;
            }
            $context_name = preg_match('/\_[a-zA-Z0-9-]*$/', $context_slug, $m);
            $context_name = preg_replace('/\_/', '', $m);
            $context_link = site_url('/cc/context/resume/' . $context_slug);
            $icon = context_icon($context_info);
            echo <<<PQR
<li><a href="{$context_link}">{$context_info['info']['title']} <span class="{$icon}"></span></a></li>
PQR;
        }
        ?>
    </ul>
</div>

<?php
include_once _INC . 'modules/cc/views/_inc/participants.phtml';
