<?php
$attributes = array('class' => 'gf', 'id' => 'edit_context_form');
echo form_open('/cc/context/create', $attributes);
?>
<input type="hidden" name="context" id="context" value="<?php echo $context ?>" />
<label><span><?php echo lang('title'); ?></span><input type="text" name="id" id="id" maxlength="30" class="focus" /></label>
<?php include dirname(__FILE__) . '/_inc/common_form.phtml'; ?>
<div class="argt">
	<a href="<?php echo site_url('/cc/context/resume/' . $context) ?>" class="cancel"><button type="button"><?php echo lang('cancel'); ?></button></a>
	<button type="submit" value="<?php echo $mode_edition ?>"><?php echo lang($mode_edition) ?></button>
</div>
<?php
echo form_close();
