<?php
if (connected_user() !== FALSE && belongs_to('context', $context, connected_user())):
    ?>
    <ul id="context-actions">
        <?php if ($user_locking === FALSE): ?>
            <li style="position: relative">
                <a href="<?php echo site_url('/cc/context/move_form/' . $id_context . '|' . parent_context($context)) ?>" id="move_context" title="<?php echo lang('move'); ?>"></a>
                <div id="move_form" class="mdl shadow"></div>
            </li>
            <li><a href="<?php echo site_url('/cc/context/delete/' . $id_context . '|' . parent_context($context)) ?>" id="delete_context" title="<?php echo lang('delete'); ?>"></a></li>
            <li><a href="<?php echo site_url('/cc/context/modify_form/' . $context) ?>" title="<?php echo lang('edit'); ?>" id="edit_context"></a></li>
            <?php
        endif;
        ?>
    </ul>
    <?php
endif;
?>
<div class="clear"></div>
<div class="topics">
    <?php include_once _INC . 'modules/cc/views/timeline/topics.phtml' ?>
</div>
