<ul id="all_we_are">
    <?php foreach ($info_participants as $participant): ?>
        <li>
            <b><?php echo $participant['user']->name ?></b>
            <a href="mailto:<?php echo $participant['user']->email ?>"><?php echo $participant['user']->email ?></a>
            <p><?php echo $participant['user']->ts ?></p>
            <a href="<?php echo site_url('account/participant/profile/' . $participant['user']->username) ?>"><?php echo $participant['user']->username ?></a>
            <?php if (is_administrator()): ?>
                <div id="user_options">
                    <u>User options</u>
                    <p><label><input type="checkbox" name="as_administrator" class="as_administrator" value="<?php echo $participant['user']->username ?>" <?php echo $participant['participant']['type'] === 'administrator' ? 'checked' : '' ?> /> Administrator</label></p>
                    <p><label><input type="checkbox" name="activation" class="activation" value="<?php echo $participant['user']->username ?>" <?php echo ! $participant['participant']['active'] === FALSE ? 'checked' : '' ?> /> Active</label></p>
                </div>
            <?php else: ?>
                <div><?php
                    echo $participant['participant']['type'] . ' | ';
                    echo ! $participant['participant']['active'] === FALSE ? 'active' : 'not active';
                    ?></div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>